# Site settings
title: Design Portfolio
email: arnaldonunez3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Designer and Developer, specializing in front end, HTML, 
  CSS and Javascript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: arnaldonunez3
github_username:  anunez18
google_username: arnaldonunez3

permalink: /:categories/:title

links:
-title: about
url: /about
-title: work
url: /work
-title: articles
url: /articles
-title: hire me
url: /hire me
# Build settings
markdown: kramdown
